language: cpp

compiler:
    - gcc

jobs:
  include:
    - os: linux
      
      language: 
        - cpp
      
      compiler:
        - gcc
      
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - gcc-10
            - g++-10
            - cmake
      
      arch: amd64
      
      env: 
        - CMAKE_VERSION_MAJOR=3.10 CMAKE_VERSION_MINOR=0 
      
      before_script:
        - mkdir build
        - cd build
        - cmake ..
      script:
        - cmake --build .
        - make test
