jobs:
  include:
    - os: linux
      dist: trusty
      env:
        - BUILD_DIR=build

    - os: linux
      dist: xenial
      env:
        - BUILD_DIR=build
    
    - os: linux
      dist: focal 
      env:
        - BUILD_DIR=build

    - os: osx
      env:
        - BUILD_DIR=build

    - os: windows  
      env:
        - BUILD_DIR=Debug/build

language: 
  - cpp

compiler:
  - gcc

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc
      - g++
      - cmake

after_install:
  - |
    if [ ${TRAVIS_OS_NAME} == "windows" ]; \
      then choco install make; \
    fi

before_script:
  - gcc --version
  - g++ --version
  - cmake --version 
  - make --version

script:
  - make lib
  - make build
  - make test

