jobs:
  include:
    - os: linux
      dist: trusty

    - os: linux
      dist: xenial

    - os: linux
      dist: focal

    - os: windows 

    - os: osx

language: 
  - cpp

compiler:
  - gcc

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc
      - g++
      - cmake

before_script:
  - gcc --version
  - g++ --version
  - cmake --version 
  - |
    if [ ${TRAVIS_OS_NAME} == "windows" ]; then \
      export BUILD_DIR=Debug/build \
      choco install make; \
    fi
  - |
    if [ ${TRAVIS_OS_NAME} != "windows" ]; then \
      export BUILD_DIR=build; \
    fi
  - make --version

script:
  - make lib
  - make build
  - make test

