jobs:
  include:
    - os: linux
      dist: trusty
    
    - os: linux
      dist: xenial
    
    - os: linux
      dist: focal 

    - os: osx

    - os: windows  

language: 
  - cpp

compiler:
  - gcc

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc
      - g++
      - cmake

before_script:
  - |
    if [ ${TRAVIS_OS_NAME} == "windows" ]; \
      then choco install make; \
    fi
  - gcc --version
  - g++ --version
  - cmake --version 
  - make --version

script: 
  - |
    if [ ${TRAVIS_OS_NAME} != "windows" ]; \
      export BUILD_DIR=$(pwd)/build; \
    fi 
  - |
    if [ ${TRAVIS_OS_NAME} == "windows" ]; \
      export BUILD_DIR=$(pwd)/Debug/build; \
    fi
  - make lib
  - make build
  - make test
